pull_request_rules:
  # If you add the label `automerge` on a PR, it will be merged automatically
  - name: automatic merge
    conditions:
      - label = automerge
    actions:
      merge:
        method: merge

  # If you add the label `autoqueue` on a PR, it will be queued automatically
  - name: automatic queue (hotfix)
    conditions:
      - label = autoqueue
      - label = hotfix
    actions:
      queue:
        name: hotfix

  - name: automatic queue (default)
    conditions:
      - label = autoqueue
      - label != hotfix
      - label != lowprio
    actions:
      queue:
        name: default

  - name: automatic queue (lowprio)
    conditions:
      - label = autoqueue
      - label = lowprio
    actions:
      queue:
        name: lowprio

queue_rules:
  - name: hotfix
    speculative_checks: 5
    allow_inplace_checks: false
    queue_conditions: []
    # This can be queued without passing the CI
    # But we still required to pass before merging
    merge_conditions:
      - check-success = test
      - check-success = test-before-merge

  - name: default
    speculative_checks: 5
    allow_inplace_checks: false
    queue_conditions:
      - check-success = test
    merge_conditions:
      - check-success = test-before-merge

  - name: lowprio
    batch_size: 3
    batch_max_wait_time: 1 min
    allow_inplace_checks: false
    queue_conditions:
      - check-success = test
    merge_conditions:
      - check-success = test-before-merge
