name: Continuous Integration
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sleep 30

  test-before-merge:
    # Only run this job on branches created by Mergify merge queue
    if: startsWith(github.head_ref, 'mergify/merge-queue/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sleep 60